### ISSUE TITLE
Статьи для перевода

### ISSUE THREAD

**Issue by kicumkicum** [Namaskarra/Test-Lern#5]
Так сложилось, что на русском языке очень мало информации. И если по программированию ее боле менее хватает, то по тестированию ее очень мало. Поэтому нужно читать английскую литературу.

Для начала возьмем курс [Software Testing Tutorial: Free Course](https://www.guru99.com/software-testing.html).
Переводить будем не все подряд, а порциями.

Переводы оформлять в виде markdown-документов. Сохранять в директории `translations/`.
На _этап_ нужно завести свою поддиректорию.

### Testing Fundamentals. Due date: 16.11.2017
- [x] [Software Testing - Introduction - Importance](https://www.guru99.com/software-testing-introduction-importance.html)
- [x] [Seven Fundamental Principles of Testing](https://www.guru99.com/software-testing-seven-principles.html)
- [ ] [SDLC Vs STLC](https://www.guru99.com/software-testing-lifecycle.html)
- [ ] [Software Testing Life Cycle - STLC explained](https://www.guru99.com/software-testing-life-cycle.html)

**Comment by Namaskarra** [comment]
# Что такое тестирование программного обеспечения? Введение, основы и значение #
**Тестирование программного обеспечения** - это мероприятие, позволяющее проверить, соответствуют ли фактические результаты ожидаемым результатам, и гарантировать, что система программного обеспечения не имеет дефектов. Это включает в себя выполнение программной компоненты или системной компоненты для оценки одного или нескольких интересующих свойств

**Тестирование программного обеспечения** также помогает выявлять ошибки, пробелы или недостающие требования вопреки фактическим требованиям. Его можно выполнить вручную или с помощью автоматизированных инструментов. Некоторые предпочитают говорить тестирование ПО белоящечное и черноящечное

**Почему важна проверка программного обеспечения?**
Тестирование важно, потому что ошибки программного обеспечения могут быть дорогими или даже опасными. Ошибки программного обеспечения могут потенциально вызвать денежные потери и человеческие потери, история полна таких примеров.
- в апреле 2015 года терминал Bloomberg в Лондоне разбился из-за сбоя программного обеспечения, затронувшего более 300 000 трейдеров на финансовых рынках. Это вынудило правительство отложить продажу долга на 3 млрд фунтов
- автомобили Nissan должны отозвать более 1 миллиона автомобилей с рынка из-за сбоя программного обеспечения в сенсорных датчиках подушки безопасности. Сообщается о двух авариях из-за этого отказа программного обеспечения
- Starbucks был вынужден закрыть около 60 % магазинов в США и Канаде из-за сбоя программного обеспечения в своей POS-системе. В какой-то момент магазин подавал кофе бесплатно, так как они не могли обработать транзакцию
- некоторые из сторонних розничных продавцов Amazon увидели, что их цена на продукт снижена до 1p из-за сбоя программного обеспечения. Они остались с большими потерями
- уязвимость в окне 10. Эта ошибка позволяет пользователям бежать из изолированной программной среды из-за недостатка в системе win32k
- в 2015 году самолет-истребитель F-35 стал жертвой ошибки программного обеспечения, из-за чего он не смог правильно определить цели
- авиакомпания China Airlines Airbus A300 потерпела крах из-за ошибки программного обеспечения 26 апреля 1994 года, в результате чего погибло 264 невинных жителя
- в 1985 году канадская терапевтическая машина Therac-25 потерпела неудачу из-за ошибки программного обеспечения и доставила пациентам летальные дозы облучения, в результате чего 3 человека погибли и получили серьезные повреждения 3 человека
- в апреле 1999 года ошибка программного обеспечения вызвала отказ от запуска военного спутника стоимостью 1,2 миллиарда долларов, самый дорогой случай в истории
- в мае 1996 года ошибка программного обеспечения привела к тому, что банковские счета 823 клиентов крупного банка США были зачислены на сумму 920 миллионов долларов США

**Типы тестирования программного обеспечения**
Обычно тестирование классифицируется по трем категориям:
1. Функциональное тестирование
2. Нефункциональное тестирование или тестирование производительности
3. Техническое обслуживание (регрессия и техническое обслуживание) (тестирование спецификаций?)

Категории делятся на подкатегории: 
1. Функциональное тестирование
- Unit Testing
- интеграционное тестирование
- дымовое тестирование
- UAT (пользовательское тестирование)
- тестирование локальное (компонентное?)
- тестирование глобальное (системное?)
- тестирование совместимости
- и др.

2. Нефункциональное тестирование
- тестирование стабильности
- стресс-тестирование
- нагрузочное тестирование
- тестирование производительности
- масштабируемость
- тестирование удобства использования
- и др.

3. Техническое обслуживание (тестирование спецификаций?)
- регрессионное тестирование
- техническое обслуживание

Это неполный список. В него можно включить еще как минимум 150 видов тестирования, список пополняется

**Comment by Namaskarra** [comment]
# 7 принципов тестирования программного обеспечения #
1. Исчерпывающее тестирование невозможно

Да! Исчерпывающее тестирование невозможно. Вместо этого нам нужен оптимальный объем тестирования, основанный на оценке риска приложения. И вопрос в миллион долларов, как вы определяете этот риск? На ваш взгляд, какая операция, скорее всего, приведет к сбою вашей операционной системы? Я уверен, что большинство из вас догадались, одновременно открыв 10 разных приложений. Поэтому, если вы тестируете эту операционную систему, вы поймете, что дефекты, вероятно, будут обнаружены в многозадачной деятельности и должны быть тщательно протестированы, что приведет нас к следующему принципу Дефектная кластеризация

2. Дефектная кластеризация

Дефектная кластеризация, в которой указано, что небольшое количество модулей содержит большинство обнаруженных дефектов. Это применение принципа Парето к тестированию программного обеспечения: примерно 80% проблем обнаруживается в 20% модулей. По опыту вы можете идентифицировать такие рискованные модули. Но этот подход имеет свои проблемы. Если одни и те же тесты повторяются снова и снова, в конечном итоге те же самые тестовые примеры больше не будут находить новые ошибки

3. Пестицидный парадокс

Повторное использование одной и той же смеси пестицидов для уничтожения насекомых во время сельского хозяйства со временем приведет к тому, что насекомые проявят устойчивость к пестициду. Таким образом, неэффективные пестициды на насекомых. То же самое касается тестирования программного обеспечения. Если будет проведен один и тот же набор повторяющихся тестов, метод будет бесполезен для обнаружения новых дефектов. Чтобы преодолеть это, необходимо регулярно пересматривать и пересматривать тестовые примеры, добавляя новые и различные тестовые примеры, чтобы найти больше дефектов. Тестеры не могут просто зависеть от существующих методов тестирования. Он должен постоянно следить за улучшением существующих методов, чтобы сделать тестирование более эффективным. Но даже после всего этого пота и тяжелой работы в тестировании вы никогда не сможете утверждать, что ваш продукт без ошибок.

4. Тестирование показывает наличие дефектов

Следовательно, принцип тестирования гласит, что тестирование говорит о наличии дефектов и не говорит об отсутствии дефектов, т.е. тестирование программного обеспечения снижает вероятность обнаружения неоткрытых дефектов в программном обеспечении, но даже если дефекты не обнаружены, это не является доказательством правильности. Но что делать, если вы работаете очень усердно, принимая все меры предосторожности и делаете ваш программный продукт 99% без ошибок. И программное обеспечение не отвечает потребностям и требованиям клиентов. Это приводит нас к следующему принципу, который гласит: отсутствие ошибок

5. Отсутствие ошибки

Возможно, программное обеспечение, которое на 99% без ошибок, по-прежнему непригодно. Это может иметь место, если система тщательно протестирована для неправильного требования. Тестирование программного обеспечения - это не просто поиск дефектов, но и проверка того, что программное обеспечение отвечает потребностям бизнеса. Отсутствие ошибки является ошибочным, т.е. обнаружение и исправление дефектов не помогает, если сборка системы непригодна и не отвечает потребностям и требованиям пользователя.Чтобы решить эту проблему, следующий принцип тестирования гласит о важности раннего тестирования

6. Раннее тестирование

Тестирование должно начинаться как можно раньше в жизненном цикле разработки программного обеспечения. Так что любые дефекты в требованиях или этапе проектирования фиксируются на ранних стадиях. Гораздо дешевле исправить дефект на ранних этапах тестирования. Но как рано нужно начинать тестирование? Рекомендуется начать поиск ошибки в момент определения требований.

7. Тестирование документации

Тестирование зависит от документации, что в основном означает, что способ тестирования сайта электронной коммерции будет отличаться от того, как вы тестируете коммерческое приложение с полки. Все разработанные программы не идентичны. Вы можете использовать другой подход, методологии, методы и типы тестирования в зависимости от типа приложения. Например, тестирование, любая POS-система в розничном магазине будет отличаться от тестирования ATM-машины.

**Comment by Namaskarra** [comment]
# Что такое V-модель? Изучите пример с использованием SDLC и STLC #
